# Generated by Django 5.0.6 on 2024-06-29 12:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResetPasswordCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('private_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('is_confirmation', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
