# Generated by Django 4.2.13 on 2024-07-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_category_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
