# Generated by Django 4.2.13 on 2024-07-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_category_slug_resource_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
