# Generated by Django 4.2.13 on 2024-07-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_category_slug_alter_resource_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='permission',
        ),
        migrations.AddField(
            model_name='resource',
            name='auditoria',
            field=models.CharField(choices=[('all', 'Barcha uchun'), ('students', "O'quvchilar uchun"), ('teachers', "O'qituvchilar uchun")], default='all', max_length=30, verbose_name='Ruxsat'),
        ),
    ]
