# Generated by Django 4.2.13 on 2024-07-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_remove_resource_permission_resource_auditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.AddField(
            model_name='resource',
            name='original_file',
            field=models.FileField(default=1, upload_to='pdfs/originals/', verbose_name='Fayl yuklash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='watermarked_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/watermarkeds/'),
        ),
    ]
