# Generated by Django 4.2.13 on 2024-07-15 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_remove_resource_file_resource_original_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='original_file',
            field=models.FileField(upload_to='pdfs/originals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Fayl yuklash'),
        ),
    ]
