# Generated by Django 4.2.13 on 2024-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_resource_original_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
