# Generated by Django 4.2.13 on 2024-07-27 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_resource_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resurslar', to='resources.resourcetype', verbose_name='Resurs turi'),
        ),
    ]
