# Generated by Django 4.2.13 on 2024-07-07 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_remove_resource_file_resource_original_file_and_more'),
        ('home', '0003_alter_favourite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='resources.resource'),
        ),
    ]
