# Generated by Django 4.2.13 on 2024-07-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='code',
            field=models.TextField(default='def solution():\n    # Write your formula here\n    return 0\n'),
        ),
    ]
