# Generated by Django 4.2.13 on 2024-07-06 13:47

from django.db import migrations
import python_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0002_alter_formula_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='source',
            field=python_field.fields.PythonCodeField(blank=True, null=True),
        ),
    ]
