# Generated by Django 4.2.13 on 2024-07-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0003_formula_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='source',
        ),
    ]
