# Generated by Django 4.2.13 on 2024-07-06 19:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0004_remove_formula_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='code',
            field=models.TextField(default='def solution(a):\n    # Write your formula here\n    result = a ** 2\n    return result\n'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='formula',
            field=ckeditor.fields.RichTextField(default='<p>a<sup>2</sup></p>'),
        ),
    ]
