# Generated by Django 4.2.13 on 2024-07-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0006_alter_formula_code_alter_formula_formula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='latex_data',
            field=models.TextField(default='', verbose_name='Latex Data'),
        ),
    ]
