# Generated by Django 4.2.13 on 2024-07-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0008_remove_formula_formula_alter_formula_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunksionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='funksional_datas/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='formula',
            name='file',
        ),
    ]
